### ISSUE TITLE
Decompiler selector bug

### ISSUE THREAD

**Issue by MPeti1** [niranjan94/show-java#155]
After I've selected an app, only CFR decompiler shows up as an option
![](https://i.imgur.com/CpDKXqL.png)

**Comment by niranjan94** [comment]
Hi ... This is not a bug. JaDX and Fernflower is available only on android devices running Android 7.0 and above. 

Please see the [compatibility matrix](https://github.com/niranjan94/show-java#compatibility-matrix) for more information. This is due to the fact that JaDX and fernflower use newer Java features that are unsupported in older versions of Android.
