### ISSUE TITLE
Bug in dex2jar module

### ISSUE THREAD

**Issue by andrew-boyarshin** [niranjan94/show-java#26]
Expected: many packages in jar.
Actual: not all packages and classes are present in jar, so Fernflower and CFR doesn't decompile them.
App: Flud - torrent downloader from Google Play. A couple of mine apps (in fact, doesn't decompile them, only a couple of 3rd-party libs I used).
Steps to represent:
1. Use 2.0.9 or later version (previous not tested).
2. Decompile app with JaDX. Look at the package structure.
3. Decompile app with other decompilers. Compare package structure. Some packages are missing.
OS:
Android 5.1.1 Lollipop (CM 12.1)
Samsung Galaxy Ace 2 (GT-I8160)
ShowJava latest (2.1.0 at the present time).

**Comment by niranjan94** [comment]
Hi ... Can you please be more clear ? ... You're saying Fernflower and CFR miss some classes while JaDX doesn't ?

**Comment by STALKER2010** [comment]
Well, FF and CFR can't decompile classes and packages just because these classes and packages simply doesn't exist in JAR! So the problem is related to dex2jar, as JaDEX, which works diectly with dex does everything correct.
https://drive.google.com/file/d/0BwXCnz8ZkxDCSG45QUVhMkdTQTA/view?usp=sharing
Post Machine app written by me (WIP). dex2jar doesn't convert to jar most of app's classes.

**Comment by niranjan94** [comment]
Okay ... :smile: Thanks for pointing out .. Will see if I can fix it in anyway ...

**Comment by Charles6666** [comment]
Bug  like they don't owe hear.

**Comment by Charles6666** [comment]
Hear it is there stealing mine cash with error me and lieing bug's

**Comment by Charles6666** [comment]
And they left Buggy
